services:
  - type: web
    name: da-wx-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn wx_live_backend:app --host 0.0.0.0 --port \
    autoDeploy: true
